#!/usr/bin/env bash
# Regenerate Python gRPC stubs from reverse-engineered proto definitions.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROTO_DIR="$ROOT/maison_protegee/proto"
OUT_DIR="$ROOT/maison_protegee/generated"

python3 -m grpc_tools.protoc \
  -I "$PROTO_DIR" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$PROTO_DIR/erable.proto"

# Fix absolute import generated by protoc
sed -i '' 's/^import erable_pb2/from . import erable_pb2/' "$OUT_DIR/erable_pb2_grpc.py" 2>/dev/null \
  || sed -i 's/^import erable_pb2/from . import erable_pb2/' "$OUT_DIR/erable_pb2_grpc.py"

echo "Generated stubs in $OUT_DIR"
"$ROOT/scripts/sync_ha_lib.sh"
